# init_x: -3
# init_y: 0
# init_z: -0.3
init_yaw: 0.0
init_q1: 0
init_q2: 0.2431
init_q3: -0.97
# init_q1: 0
# init_q2: 0
# init_q3: -1
noise_payload: 0.00
noise_uav: 0.00
noise_vel_payload: 0.00
noise_vel_uav: 0.00
simulation_rate: 1000
odom_rate: 400
g: 9.81
mass: 1.2
Ixx: 2.64e-3
Iyy: 2.64e-3
Izz: 4.96e-3
kf: 8.98132e-8
prop_radius: 0.062
arm_length: 0.26
motor_time_constant: 0.003333
max_rpm: 45000.0
min_rpm: 120.0

payload_size: 0.1
mass_load: 0.126
l_length: 0.644

kOmega: [4.0, 4.0, 4.0]
kdOmega: [15.0, 15.0, 15.0]